//! import "Data\Enums\ETile.j"
//! import "Data\Enums\ESkillData.j"
//! import "Data\Enums\EResource.j"
//! import "Data\InitializeObjects\DataBaseSkill.j"
//! loaddata "Data\SkillData.slk"
//! import "Data\SkillDataStr.j"
//! import "System\Hunting.j"
//! import "System\IResource.j"